// счетчик айди 
let cardCounter = 1;

const miniCardProduct = [
   // ==========  category: 'new-discounts',
   {
      id: cardCounter++,
      category: 'new-discounts',
      name: 'Сандалі',
      brand: 'DeeZee',
      img: 'new-discounts/DeeZee.png',
      price: 339,
      oldPrice: 560,
   },
   {
      id: cardCounter++,
      category: 'new-discounts',
      name: 'В єтнамки',
      brand: 'Colin s ',
      img: 'new-discounts/Colins.png',
      price: 152,
      oldPrice: 349,
   },
   {
      id: cardCounter++,
      category: 'new-discounts',
      name: 'Срібна каблучка',
      brand: 'Golden Silver',
      img: 'new-discounts/GoldenSilver.png',
      price: 1473 ,
      oldPrice: 2782,
   },
   {
      id: cardCounter++,
      category: 'new-discounts',
      name: 'Шльопанці',
      brand: 'No Brand',
      img: 'new-discounts/Flip.png',
      price: 349,
      oldPrice: 488,
   },
   {
      id: cardCounter++,
      category: 'new-discounts',
      name: 'Футболка',
      brand: 'No Brand',
      img: 'new-discounts/Roza.png',
      price: 138,
      oldPrice: 380,
   },
   {
      id: cardCounter++,
      category: 'new-discounts',
      name: 'Набір шкарпеток',
      brand: 'Rovix',
      img: 'new-discounts/Rovix.png',
      price: 299,
      oldPrice: 450,
   },
   //  =============    category: 'top-discount',
   {
      id: cardCounter++,
      category: 'top-discount',
      name: 'Кросівки',
      brand: 'Bravi',
      img: 'top-discount/Bravi.png',
      price: 1145,
      oldPrice: 1510,
   },
   {
      id: cardCounter++,
      category: 'top-discount',
      name: 'Кросівки',
      brand: 'Violeta',
      img: 'top-discount/Violeta.png',
      price: 345,
      oldPrice: 800,
   },
   {
      id: cardCounter++,
      category: 'top-discount',
      name: 'Спідня білизна',
      brand: 'BASIC TRUNK',
      img: 'top-discount/Basic.png',
      price: 470 ,
      oldPrice: 635,
   },
   {
      id: cardCounter++,
      category: 'top-discount',
      name: 'Спідня білизна',
      brand: 'Men s Multi',
      img: 'top-discount/Multi.png',
      price: 349,
      oldPrice: 488,
   },
   {
      id: cardCounter++,
      category: 'top-discount',
      name: 'Черевики',
      brand: 'One Way',
      img: 'top-discount/Way.png',
      price: 1550,
      oldPrice: 1999,
   },
   {
      id: cardCounter++,
      category: 'top-discount',
      name: 'Трусики',
      brand: 'Victoria s Secret',
      img: 'top-discount/Secret.png',
      price: 409,
      oldPrice: 700,
   },
   // ==============    category: 'popular-discount',
   {
      id: cardCounter++,
      category: 'popular-discount',
      name: 'Шорти',
      brand: 'Malta',
      img: 'popular-discount/Malta.png',
      price: 110,
      oldPrice: 199,
   },
   {
      id: cardCounter++,
      category: 'popular-discount',
      name: 'Магніт',
      brand: 'No Brand',
      img: 'popular-discount/Mag.png',
      price: 27,
      oldPrice: 45,
   },
   {
      id: cardCounter++,
      category: 'popular-discount',
      name: 'Віночок',
      brand: 'Esmara',
      img: 'popular-discount/Esmara.png',
      price: 94 ,
      oldPrice: 135,
   },
   {
      id: cardCounter++,
      category: 'popular-discount',
      name: 'Харчовий контейнер',
      brand: 'Violet House',
      img: 'popular-discount/House.png',
      price: 47,
      oldPrice: 105,
   },
   {
      id: cardCounter++,
      category: 'popular-discount',
      name: 'Шкарпетки',
      brand: 'GoSocks',
      img: 'popular-discount/GoSocks.png',
      price: 18,
      oldPrice: 14,
   },
   {
      id: cardCounter++,
      category: 'popular-discount',
      name: 'Мило туалетне',
      brand: 'No Brand',
      img: 'popular-discount/Ml.png',
      price: 74,
      oldPrice: 111,
   },
   // ==============    category: 'new-t-shirts',
   {
      id: cardCounter++,
      category: 'new-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'new-t-shirts/Sol.png',
      price: 339,
      oldPrice: 759,
   },
   {
      id: cardCounter++,
      category: 'new-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'new-t-shirts/Sol.png',
      price: 339,
      oldPrice: 759,    
   },
   {
      id: cardCounter++,
      category: 'new-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'new-t-shirts/Sol.png',
      price: 339,
      oldPrice: 759,    
   },
   {
      id: cardCounter++,
      category: 'new-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'new-t-shirts/Sol.png',
      price: 339,
      oldPrice: 759,    
   },
   {
      id: cardCounter++,
      category: 'new-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'new-t-shirts/Sol.png',
      price: 339,
      oldPrice: 759,    
   },
   {
      id: cardCounter++,
      category: 'new-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'new-t-shirts/Sol.png',
      price: 339,
      oldPrice: 759,    
   },
   // ==============    category: 'top-t-shirts',
   {
      id: cardCounter++,
      category: 'top-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'top-t-shirts/Game.png',
      price: 349,
      oldPrice: 821,
   },
   {
      id: cardCounter++,
      category: 'top-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'top-t-shirts/Game.png',
      price: 349,
      oldPrice: 821,
   },
   {
      id: cardCounter++,
      category: 'top-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'top-t-shirts/Game.png',
      price: 349,
      oldPrice: 821,
   },
   {
      id: cardCounter++,
      category: 'top-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'top-t-shirts/Game.png',
      price: 349,
      oldPrice: 821,
   },
   {
      id: cardCounter++,
      category: 'top-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'top-t-shirts/Game.png',
      price: 349,
      oldPrice: 821,
   },
   {
      id: cardCounter++,
      category: 'top-t-shirts',
      name: 'Футболка',
      brand: 'Sol s',
      img: 'top-t-shirts/Game.png',
      price: 349,
      oldPrice: 821,
   },
   // ==============    category: 'popular-t-shirts',
   {
      id: cardCounter++,
      category: 'popular-t-shirts',
      name: 'Футболка',
      brand: 'Barber',
      img: 'popular-t-shirts/Barber.png',
      price: 465,
      oldPrice: 999,
   },
   {
      id: cardCounter++,
      category: 'popular-t-shirts',
      name: 'Футболка',
      brand: 'Barber',
      img: 'popular-t-shirts/Barber.png',
      price: 465,
      oldPrice: 999,   
   },
   {
      id: cardCounter++,
      category: 'popular-t-shirts',
      name: 'Футболка',
      brand: 'Barber',
      img: 'popular-t-shirts/Barber.png',
      price: 465,
      oldPrice: 999,   
   },
   {
      id: cardCounter++,
      category: 'popular-t-shirts',
      name: 'Футболка',
      brand: 'Barber',
      img: 'popular-t-shirts/Barber.png',
      price: 465,
      oldPrice: 999,   
   }, 
   {
      id: cardCounter++,
      category: 'popular-t-shirts',
      name: 'Футболка',
      brand: 'Barber',
      img: 'popular-t-shirts/Barber.png',
      price: 465,
      oldPrice: 999,   
   },
   {
      id: cardCounter++,
      category: 'popular-t-shirts',
      name: 'Футболка',
      brand: 'Barber',
      img: 'popular-t-shirts/Barber.png',
      price: 465,
      oldPrice: 999,   
   },
   // ==============    category: 'new-pants',
   {
      id: cardCounter++,
      category: 'new-pants',
      name: 'Шорти',
      brand: 'CLUB JU',
      img: 'new-pants/Ju.png',
      price: 399,
      oldPrice: 550,
   },
   {
      id: cardCounter++,
      category: 'new-pants',
      name: 'Шорти',
      brand: 'CLUB JU',
      img: 'new-pants/Ju.png',
      price: 399,
      oldPrice: 550,
   },
   {
      id: cardCounter++,
      category: 'new-pants',
      name: 'Шорти',
      brand: 'CLUB JU',
      img: 'new-pants/Ju.png',
      price: 399,
      oldPrice: 550,
   },
   {
      id: cardCounter++,
      category: 'new-pants',
      name: 'Шорти',
      brand: 'CLUB JU',
      img: 'new-pants/Ju.png',
      price: 399,
      oldPrice: 550,
   },
   {
      id: cardCounter++,
      category: 'new-pants',
      name: 'Шорти',
      brand: 'CLUB JU',
      img: 'new-pants/Ju.png',
      price: 399,
      oldPrice: 550,
   },
   {
      id: cardCounter++,
      category: 'new-pants',
      name: 'Шорти',
      brand: 'CLUB JU',
      img: 'new-pants/Ju.png',
      price: 399,
      oldPrice: 550,
   },
   // ==============    category: 'top-pants',
   {
      id: cardCounter++,
      category: 'top-pants',
      name: 'Шорти',
      brand: 'New Balance',
      img: 'top-pants/New.png',
      price: 1597,
      oldPrice: 2100,
   },
   {
      id: cardCounter++,
      category: 'top-pants',
      name: 'Шорти',
      brand: 'New Balance',
      img: 'top-pants/New.png',
      price: 1597,
      oldPrice: 2100,
   },
   {
      id: cardCounter++,
      category: 'top-pants',
      name: 'Шорти',
      brand: 'New Balance',
      img: 'top-pants/New.png',
      price: 1597,
      oldPrice: 2100,
   },
   {
      id: cardCounter++,
      category: 'top-pants',
      name: 'Шорти',
      brand: 'New Balance',
      img: 'top-pants/New.png',
      price: 1597,
      oldPrice: 2100,
   },
   {
      id: cardCounter++,
      category: 'top-pants',
      name: 'Шорти',
      brand: 'New Balance',
      img: 'top-pants/New.png',
      price: 1597,
      oldPrice: 2100,
   },
   {
      id: cardCounter++,
      category: 'top-pants',
      name: 'Шорти',
      brand: 'New Balance',
      img: 'top-pants/New.png',
      price: 1597,
      oldPrice: 2100,
   },
   // ==============    category: 'popular-pants',
   {
      id: cardCounter++,
      category: 'popular-pants',
      name: 'Шорти',
      brand: 'KOTON',
      img: 'popular-pants/Koton.png',
      price: 234,
      oldPrice: 555,
   },
   {
      id: cardCounter++,
      category: 'popular-pants',
      name: 'Шорти',
      brand: 'KOTON',
      img: 'popular-pants/Koton.png',
      price: 234,
      oldPrice: 555,
   },
   {
      id: cardCounter++,
      category: 'popular-pants',
      name: 'Шорти',
      brand: 'KOTON',
      img: 'popular-pants/Koton.png',
      price: 234,
      oldPrice: 555,
   },
   {
      id: cardCounter++,
      category: 'popular-pants',
      name: 'Шорти',
      brand: 'KOTON',
      img: 'popular-pants/Koton.png',
      price: 234,
      oldPrice: 555,
   },
   {
      id: cardCounter++,
      category: 'popular-pants',
      name: 'Шорти',
      brand: 'KOTON',
      img: 'popular-pants/Koton.png',
      price: 234,
      oldPrice: 555,
   },
   {
      id: cardCounter++,
      category: 'popular-pants',
      name: 'Шорти',
      brand: 'KOTON',
      img: 'popular-pants/Koton.png',
      price: 234,
      oldPrice: 555,
   },
   // ==============    category: 'new-dresses',
   {
      id: cardCounter++,
      category: 'new-dresses',
      name: 'Сукня',
      brand: 'Stories',
      img: 'new-dresses/Stories.png',
      price: 1020,
      oldPrice: 1800,
   },
   {
      id: cardCounter++,
      category: 'new-dresses',
      name: 'Сукня',
      brand: 'Stories',
      img: 'new-dresses/Stories.png',
      price: 1020,
      oldPrice: 1800,
   },
   {
      id: cardCounter++,
      category: 'new-dresses',
      name: 'Сукня',
      brand: 'Stories',
      img: 'new-dresses/Stories.png',
      price: 1020,
      oldPrice: 1800,
   },
   {
      id: cardCounter++,
      category: 'new-dresses',
      name: 'Сукня',
      brand: 'Stories',
      img: 'new-dresses/Stories.png',
      price: 1020,
      oldPrice: 1800,
   },
   {
      id: cardCounter++,
      category: 'new-dresses',
      name: 'Сукня',
      brand: 'Stories',
      img: 'new-dresses/Stories.png',
      price: 1020,
      oldPrice: 1800,
   },
   {
      id: cardCounter++,
      category: 'new-dresses',
      name: 'Сукня',
      brand: 'Stories',
      img: 'new-dresses/Stories.png',
      price: 1020,
      oldPrice: 1800,
   },
   // ==============    category: 'top-dresses',
   {
      id: cardCounter++,
      category: 'top-dresses',
      name: 'Сукня',
      brand: 'Other',
      img: 'top-dresses/Other.png',
      price: 1360,
      oldPrice: 2400,
   },
   {
      id: cardCounter++,
      category: 'top-dresses',
      name: 'Сукня',
      brand: 'Other',
      img: 'top-dresses/Other.png',
      price: 1360,
      oldPrice: 2400,
   },
   {
      id: cardCounter++,
      category: 'top-dresses',
      name: 'Сукня',
      brand: 'Other',
      img: 'top-dresses/Other.png',
      price: 1360,
      oldPrice: 2400,
   },
   {
      id: cardCounter++,
      category: 'top-dresses',
      name: 'Сукня',
      brand: 'Other',
      img: 'top-dresses/Other.png',
      price: 1360,
      oldPrice: 2400,
   },
   {
      id: cardCounter++,
      category: 'top-dresses',
      name: 'Сукня',
      brand: 'Other',
      img: 'top-dresses/Other.png',
      price: 1360,
      oldPrice: 2400,
   },
   {
      id: cardCounter++,
      category: 'top-dresses',
      name: 'Сукня',
      brand: 'Other',
      img: 'top-dresses/Other.png',
      price: 1360,
      oldPrice: 2400,
   },
   // ==============    category: 'popular-dresses',
   {
      id: cardCounter++,
      category: 'popular-dresses',
      name: 'Шорти',
      brand: 'Sec',
      img: 'popular-dresses/Sec.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      category: 'popular-dresses',
      name: 'Шорти',
      brand: 'Sec',
      img: 'popular-dresses/Sec.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      id: cardCounter++,
      category: 'popular-dresses',
      name: 'Шорти',
      brand: 'Sec',
      img: 'popular-dresses/Sec.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      id: cardCounter++,
      category: 'popular-dresses',
      name: 'Шорти',
      brand: 'Sec',
      img: 'popular-dresses/Sec.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      id: cardCounter++,
      category: 'popular-dresses',
      name: 'Шорти',
      brand: 'Sec',
      img: 'popular-dresses/Sec.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      id: cardCounter++,
      category: 'popular-dresses',
      name: 'Шорти',
      brand: 'Sec',
      img: 'popular-dresses/Sec.png',
      price: 1360,
      oldPrice: 2220,
   },
   // ==============    category: 'new-glasses',
   {
      id: cardCounter++,
      category: 'new-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'new-glasses/Marioni.png',
      price: 336,
      oldPrice: 689,
   },
   {
      id: cardCounter++,
      category: 'new-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'new-glasses/Marioni.png',
      price: 336,
      oldPrice: 689,
   },
   {
      id: cardCounter++,
      category: 'new-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'new-glasses/Marioni.png',
      price: 336,
      oldPrice: 689,
   },
   {
      id: cardCounter++,
      category: 'new-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'new-glasses/Marioni.png',
      price: 336,
      oldPrice: 689,
   },
   {
      id: cardCounter++,
      category: 'new-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'new-glasses/Marioni.png',
      price: 336,
      oldPrice: 689,
   },
   {
      id: cardCounter++,
      category: 'new-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'new-glasses/Marioni.png',
      price: 336,
      oldPrice: 689,
   },
   // ==============    category: 'top-glasses',
   {
      id: cardCounter++,
      category: 'top-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Luoweite',
      img: 'top-glasses/Luoweite.png',
      price: 336,
      oldPrice: 1222,
   },
   {
      id: cardCounter++,
      category: 'top-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Luoweite',
      img: 'top-glasses/Luoweite.png',
      price: 336,
      oldPrice: 1222,
   },
   {
      id: cardCounter++,
      category: 'top-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Luoweite',
      img: 'top-glasses/Luoweite.png',
      price: 336,
      oldPrice: 1222,
   },
   {
      id: cardCounter++,
      category: 'top-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Luoweite',
      img: 'top-glasses/Luoweite.png',
      price: 336,
      oldPrice: 1222,
   },
   {
      id: cardCounter++,
      category: 'top-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Luoweite',
      img: 'top-glasses/Luoweite.png',
      price: 336,
      oldPrice: 1222,
   },
   {
      id: cardCounter++,
      category: 'top-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Luoweite',
      img: 'top-glasses/Luoweite.png',
      price: 336,
      oldPrice: 1222,
   },
   // ==============    category: 'popular-glasses',
   {
      id: cardCounter++,
      category: 'popular-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'popular-glasses/Gabriela.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      category: 'popular-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'popular-glasses/Gabriela.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      category: 'popular-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'popular-glasses/Gabriela.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      category: 'popular-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'popular-glasses/Gabriela.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      category: 'popular-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'popular-glasses/Gabriela.png',
      price: 1360,
      oldPrice: 2220,
   },
   {
      id: cardCounter++,
      category: 'popular-glasses',
      name: 'Сонцезахисні окуляри',
      brand: 'Gabriela Marioni',
      img: 'popular-glasses/Gabriela.png',
      price: 1360,
      oldPrice: 2220,
   },
   // ==============    category: 'new-stuff',
   {
      id: cardCounter++,
      category: 'new-stuff',
      name: 'Сорочка',
      brand: 'KOTON',
      img: 'new-stuff/Koton.png',
      price: 129,
      oldPrice: 399,
   },
   {
      id: cardCounter++,
      category: 'new-stuff',
      name: 'Сорочка',
      brand: 'KOTON',
      img: 'new-stuff/Koton.png',
      price: 129,
      oldPrice: 399,
   },
   {
      id: cardCounter++,
      category: 'new-stuff',
      name: 'Сорочка',
      brand: 'KOTON',
      img: 'new-stuff/Koton.png',
      price: 129,
      oldPrice: 399,
   },
   {
      id: cardCounter++,
      category: 'new-stuff',
      name: 'Сорочка',
      brand: 'KOTON',
      img: 'new-stuff/Koton.png',
      price: 129,
      oldPrice: 399,
   },
   {
      id: cardCounter++,
      category: 'new-stuff',
      name: 'Сорочка',
      brand: 'KOTON',
      img: 'new-stuff/Koton.png',
      price: 129,
      oldPrice: 399,
   },
   {
      id: cardCounter++,
      category: 'new-stuff',
      name: 'Сорочка',
      brand: 'KOTON',
      img: 'new-stuff/Koton.png',
      price: 129,
      oldPrice: 399,
   },
   // ==============    category: 'top-stuff',
   {
      id: cardCounter++,
      category: 'top-stuff',
      name: 'Сукня',
      brand: 'Sasha',
      img: 'top-stuff/Sasha.png',
      price: 219,
      oldPrice: 400,
   },
   {
      id: cardCounter++,
      category: 'top-stuff',
      name: 'Сукня',
      brand: 'Sasha',
      img: 'top-stuff/Sasha.png',
      price: 219,
      oldPrice: 400,
   },
   {
      id: cardCounter++,
      category: 'top-stuff',
      name: 'Сукня',
      brand: 'Sasha',
      img: 'top-stuff/Sasha.png',
      price: 219,
      oldPrice: 400,
   },
   {
      id: cardCounter++,
      category: 'top-stuff',
      name: 'Сукня',
      brand: 'Sasha',
      img: 'top-stuff/Sasha.png',
      price: 219,
      oldPrice: 400,
   },
   {
      id: cardCounter++,
      category: 'top-stuff',
      name: 'Сукня',
      brand: 'Sasha',
      img: 'top-stuff/Sasha.png',
      price: 219,
      oldPrice: 400,
   },
   {
      id: cardCounter++,
      category: 'top-stuff',
      name: 'Сукня',
      brand: 'Sasha',
      img: 'top-stuff/Sasha.png',
      price: 219,
      oldPrice: 400,
   },
   // ==============    category: 'popular-stuff',
   {
      id: cardCounter++,
      category: 'popular-stuff',
      name: 'Набір косметики',
      brand: 'Kimi',
      img: 'popular-stuff/Kimi.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-stuff',
      name: 'Набір косметики',
      brand: 'Kimi',
      img: 'popular-stuff/Kimi.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-stuff',
      name: 'Набір косметики',
      brand: 'Kimi',
      img: 'popular-stuff/Kimi.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-stuff',
      name: 'Набір косметики',
      brand: 'Kimi',
      img: 'popular-stuff/Kimi.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-stuff',
      name: 'Набір косметики',
      brand: 'Kimi',
      img: 'popular-stuff/Kimi.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-stuff',
      name: 'Набір косметики',
      brand: 'Kimi',
      img: 'popular-stuff/Kimi.png',
      price: 174,
      oldPrice: 451,
   },
   // ==============    category: 'new-backpacks'
   {
      id: cardCounter++,
      category: 'new-backpacks',
      name: 'Рюкзак',
      brand: 'Fashion',
      img: 'new-backpacks/Fashion.png',
      price: 1200,
      oldPrice: 1500,
   },
   {
      id: cardCounter++,
      category: 'new-backpacks',
      name: 'Рюкзак',
      brand: 'Fashion',
      img: 'new-backpacks/Fashion.png',
      price: 1200,
      oldPrice: 1500,
   },
   {
      id: cardCounter++,
      category: 'new-backpacks',
      name: 'Рюкзак',
      brand: 'Fashion',
      img: 'new-backpacks/Fashion.png',
      price: 1200,
      oldPrice: 1500,
   },
   {
      id: cardCounter++,
      category: 'new-backpacks',
      name: 'Рюкзак',
      brand: 'Fashion',
      img: 'new-backpacks/Fashion.png',
      price: 1200,
      oldPrice: 1500,
   },
   {
      id: cardCounter++,
      category: 'new-backpacks',
      name: 'Рюкзак',
      brand: 'Fashion',
      img: 'new-backpacks/Fashion.png',
      price: 1200,
      oldPrice: 1500,
   },
   {
      id: cardCounter++,
      category: 'new-backpacks',
      name: 'Рюкзак',
      brand: 'Fashion',
      img: 'new-backpacks/Fashion.png',
      price: 1200,
      oldPrice: 1500,
   },
   // ==============    category: 'top-backpacks'
   {
      id: cardCounter++,
      category: 'top-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'top-backpacks/Ry.png',
      price: 625,
      oldPrice: 888,
   },
   {
      id: cardCounter++,
      category: 'top-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'top-backpacks/Ry.png',
      price: 625,
      oldPrice: 888,
   },
   {
      id: cardCounter++,
      category: 'top-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'top-backpacks/Ry.png',
      price: 625,
      oldPrice: 888,
   },
   {
      id: cardCounter++,
      category: 'top-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'top-backpacks/Ry.png',
      price: 625,
      oldPrice: 888,
   },
   {
      id: cardCounter++,
      category: 'top-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'top-backpacks/Ry.png',
      price: 625,
      oldPrice: 888,
   },
   {
      id: cardCounter++,
      category: 'top-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'top-backpacks/Ry.png',
      price: 625,
      oldPrice: 888,
   },
   // ==============    category: 'popular-backpacks'
   {
      id: cardCounter++,
      category: 'popular-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'popular-backpacks/RyD.png',
      price: 990,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'popular-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'popular-backpacks/RyD.png',
      price: 990,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'popular-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'popular-backpacks/RyD.png',
      price: 990,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'popular-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'popular-backpacks/RyD.png',
      price: 990,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'popular-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'popular-backpacks/RyD.png',
      price: 990,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'popular-backpacks',
      name: 'Рюкзак',
      brand: 'No Brand',
      img: 'popular-backpacks/RyD.png',
      price: 990,
      oldPrice: 1200,
   },
   // ==============    category: 'new-concilaria'
   {
      id: cardCounter++,
      category: 'new-concilaria',
      name: 'Набор тетрадей',
      brand: 'Lidl',
      img: 'new-concilaria/Lidl.png',
      price: 20,
      oldPrice: 65,
   },
   {
      id: cardCounter++,
      category: 'new-concilaria',
      name: 'Набор тетрадей',
      brand: 'Lidl',
      img: 'new-concilaria/Lidl.png',
      price: 20,
      oldPrice: 65,
   },
   {
      id: cardCounter++,
      category: 'new-concilaria',
      name: 'Набор тетрадей',
      brand: 'Lidl',
      img: 'new-concilaria/Lidl.png',
      price: 20,
      oldPrice: 65,
   },
   {
      id: cardCounter++,
      category: 'new-concilaria',
      name: 'Набор тетрадей',
      brand: 'Lidl',
      img: 'new-concilaria/Lidl.png',
      price: 20,
      oldPrice: 65,
   },
   {
      id: cardCounter++,
      category: 'new-concilaria',
      name: 'Набор тетрадей',
      brand: 'Lidl',
      img: 'new-concilaria/Lidl.png',
      price: 20,
      oldPrice: 65,
   },
   {
      id: cardCounter++,
      category: 'new-concilaria',
      name: 'Набор тетрадей',
      brand: 'Lidl',
      img: 'new-concilaria/Lidl.png',
      price: 20,
      oldPrice: 65,
   },
   // ==============    category: 'top-concilaria'
   {
      id: cardCounter++,
      category: 'top-concilaria',
      name: 'Пенал',
      brand: 'No Brand',
      img: 'top-concilaria/Pen.png',
      price: 74,
      oldPrice: 151,
   },
   {
      id: cardCounter++,
      category: 'top-concilaria',
      name: 'Пенал',
      brand: 'No Brand',
      img: 'top-concilaria/Pen.png',
      price: 74,
      oldPrice: 151,
   },
   {
      id: cardCounter++,
      category: 'top-concilaria',
      name: 'Пенал',
      brand: 'No Brand',
      img: 'top-concilaria/Pen.png',
      price: 74,
      oldPrice: 151,
   },
   {
      id: cardCounter++,
      category: 'top-concilaria',
      name: 'Пенал',
      brand: 'No Brand',
      img: 'top-concilaria/Pen.png',
      price: 74,
      oldPrice: 151,
   },
   {
      id: cardCounter++,
      category: 'top-concilaria',
      name: 'Пенал',
      brand: 'No Brand',
      img: 'top-concilaria/Pen.png',
      price: 74,
      oldPrice: 151,
   },
   {
      id: cardCounter++,
      category: 'top-concilaria',
      name: 'Пенал',
      brand: 'No Brand',
      img: 'top-concilaria/Pen.png',
      price: 74,
      oldPrice: 151,
   },
   // ==============    category: 'popular-concilaria'
   {
      id: cardCounter++,
      category: 'popular-concilaria',
      name: 'Точилка',
      brand: 'Sanrio',
      img: 'popular-concilaria/Sanrio.png',
      price: 101,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-concilaria',
      name: 'Точилка',
      brand: 'Sanrio',
      img: 'popular-concilaria/Sanrio.png',
      price: 101,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-concilaria',
      name: 'Точилка',
      brand: 'Sanrio',
      img: 'popular-concilaria/Sanrio.png',
      price: 101,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-concilaria',
      name: 'Точилка',
      brand: 'Sanrio',
      img: 'popular-concilaria/Sanrio.png',
      price: 101,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-concilaria',
      name: 'Точилка',
      brand: 'Sanrio',
      img: 'popular-concilaria/Sanrio.png',
      price: 101,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-concilaria',
      name: 'Точилка',
      brand: 'Sanrio',
      img: 'popular-concilaria/Sanrio.png',
      price: 101,
      oldPrice: 451,
   },
   // ==============    category: 'new-sports'
   {
      id: cardCounter++,
      category: 'new-sports',
      name: 'Гиря спортивная',
      brand: 'Springos',
      img: 'new-sports/Springos.png',
      price: 359,
      oldPrice: 800,
   },
   {
      id: cardCounter++,
      category: 'new-sports',
      name: 'Гиря спортивная',
      brand: 'Springos',
      img: 'new-sports/Springos.png',
      price: 359,
      oldPrice: 800,
   },
   {
      id: cardCounter++,
      category: 'new-sports',
      name: 'Гиря спортивная',
      brand: 'Springos',
      img: 'new-sports/Springos.png',
      price: 359,
      oldPrice: 800,
   },
   {
      id: cardCounter++,
      category: 'new-sports',
      name: 'Гиря спортивная',
      brand: 'Springos',
      img: 'new-sports/Springos.png',
      price: 359,
      oldPrice: 800,
   },
   {
      id: cardCounter++,
      category: 'new-sports',
      name: 'Гиря спортивная',
      brand: 'Springos',
      img: 'new-sports/Springos.png',
      price: 359,
      oldPrice: 800,
   },
   {
      id: cardCounter++,
      category: 'new-sports',
      name: 'Гиря спортивная',
      brand: 'Springos',
      img: 'new-sports/Springos.png',
      price: 359,
      oldPrice: 800,
   },
   // ==============    category: 'top-sports'
   {
      id: cardCounter++,
      category: 'top-sports',
      name: 'Набор гантелей',
      brand: 'Springos',
      img: 'top-sports/Spr.png',
      price: 459,
      oldPrice: 780,
   },
   {
      id: cardCounter++,
      category: 'top-sports',
      name: 'Набор гантелей',
      brand: 'Springos',
      img: 'top-sports/Spr.png',
      price: 459,
      oldPrice: 780,
   },
   {
      id: cardCounter++,
      category: 'top-sports',
      name: 'Набор гантелей',
      brand: 'Springos',
      img: 'top-sports/Spr.png',
      price: 459,
      oldPrice: 780,
   },
   {
      id: cardCounter++,
      category: 'top-sports',
      name: 'Набор гантелей',
      brand: 'Springos',
      img: 'top-sports/Spr.png',
      price: 459,
      oldPrice: 780,
   },
   {
      id: cardCounter++,
      category: 'top-sports',
      name: 'Набор гантелей',
      brand: 'Springos',
      img: 'top-sports/Spr.png',
      price: 459,
      oldPrice: 780,
   },
   {
      id: cardCounter++,
      category: 'top-sports',
      name: 'Набор гантелей',
      brand: 'Springos',
      img: 'top-sports/Spr.png',
      price: 459,
      oldPrice: 780,
   },
   // ==============    category: 'popular-sports'
   {
      id: cardCounter++,
      category: 'popular-sports',
      name: 'Гантели сборные',
      brand: 'Rock Pro Newt',
      img: 'popular-sports/Pro.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-sports',
      name: 'Гантели сборные',
      brand: 'Rock Pro Newt',
      img: 'popular-sports/Pro.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-sports',
      name: 'Гантели сборные',
      brand: 'Rock Pro Newt',
      img: 'popular-sports/Pro.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-sports',
      name: 'Гантели сборные',
      brand: 'Rock Pro Newt',
      img: 'popular-sports/Pro.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-sports',
      name: 'Гантели сборные',
      brand: 'Rock Pro Newt',
      img: 'popular-sports/Pro.png',
      price: 174,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'popular-sports',
      name: 'Гантели сборные',
      brand: 'Rock Pro Newt',
      img: 'popular-sports/Pro.png',
      price: 174,
      oldPrice: 451,
   },
   // ==============    category: 'new-perfume'
   {
      id: cardCounter++,
      category: 'new-perfume',
      name: 'Духи Сирень',
      brand: 'L erbolario',
      img: 'new-perfume/Ler.png',
      price: 1744,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'new-perfume',
      name: 'Духи Сирень',
      brand: 'L erbolario',
      img: 'new-perfume/Ler.png',
      price: 1744,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'new-perfume',
      name: 'Духи Сирень',
      brand: 'L erbolario',
      img: 'new-perfume/Ler.png',
      price: 1744,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'new-perfume',
      name: 'Духи Сирень',
      brand: 'L erbolario',
      img: 'new-perfume/Ler.png',
      price: 1744,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'new-perfume',
      name: 'Духи Сирень',
      brand: 'L erbolario',
      img: 'new-perfume/Ler.png',
      price: 1744,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'new-perfume',
      name: 'Духи Сирень',
      brand: 'L erbolario',
      img: 'new-perfume/Ler.png',
      price: 1744,
      oldPrice: 1300,
   },
   // ==============    category: 'top-perfume'
   {
      id: cardCounter++,
      category: 'top-perfume',
      name: 'Духи',
      brand: 'Velvet Sam',
      img: 'top-perfume/Sam.png',
      price: 2500,
      oldPrice: 2999,
   },
   {
      id: cardCounter++,
      category: 'top-perfume',
      name: 'Духи',
      brand: 'Velvet Sam',
      img: 'top-perfume/Sam.png',
      price: 2500,
      oldPrice: 2999,
   },
   {
      id: cardCounter++,
      category: 'top-perfume',
      name: 'Духи',
      brand: 'Velvet Sam',
      img: 'top-perfume/Sam.png',
      price: 2500,
      oldPrice: 2999,
   },
   {
      id: cardCounter++,
      category: 'top-perfume',
      name: 'Духи',
      brand: 'Velvet Sam',
      img: 'top-perfume/Sam.png',
      price: 2500,
      oldPrice: 2999,
   },
   {
      id: cardCounter++,
      category: 'top-perfume',
      name: 'Духи',
      brand: 'Velvet Sam',
      img: 'top-perfume/Sam.png',
      price: 2500,
      oldPrice: 2999,
   },
   {
      id: cardCounter++,
      category: 'top-perfume',
      name: 'Духи',
      brand: 'Velvet Sam',
      img: 'top-perfume/Sam.png',
      price: 2500,
      oldPrice: 2999,
   },
   // ==============    category: 'popular-perfume'
   {
      id: cardCounter++,
      category: 'popular-perfume',
      name: 'Духи',
      brand: 'Victoria s Secret',
      img: 'popular-perfume/Vi.png',
      price: 732,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'popular-perfume',
      name: 'Духи',
      brand: 'Victoria s Secret',
      img: 'popular-perfume/Vi.png',
      price: 732,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'popular-perfume',
      name: 'Духи',
      brand: 'Victoria s Secret',
      img: 'popular-perfume/Vi.png',
      price: 732,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'popular-perfume',
      name: 'Духи',
      brand: 'Victoria s Secret',
      img: 'popular-perfume/Vi.png',
      price: 732,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'popular-perfume',
      name: 'Духи',
      brand: 'Victoria s Secret',
      img: 'popular-perfume/Vi.png',
      price: 732,
      oldPrice: 1300,
   },
   {
      id: cardCounter++,
      category: 'popular-perfume',
      name: 'Духи',
      brand: 'Victoria s Secret',
      img: 'popular-perfume/Vi.png',
      price: 732,
      oldPrice: 1300,
   },
   // ==============    category: 'new-car'
   {
      id: cardCounter++,
      category: 'new-car',
      name: 'Устройство "Свободные руки"',
      brand: 'Silver Crest',
      img: 'new-car/Crest.png',
      price: 708,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'new-car',
      name: 'Устройство "Свободные руки"',
      brand: 'Silver Crest',
      img: 'new-car/Crest.png',
      price: 708,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'new-car',
      name: 'Устройство "Свободные руки"',
      brand: 'Silver Crest',
      img: 'new-car/Crest.png',
      price: 708,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'new-car',
      name: 'Устройство "Свободные руки"',
      brand: 'Silver Crest',
      img: 'new-car/Crest.png',
      price: 708,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'new-car',
      name: 'Устройство "Свободные руки"',
      brand: 'Silver Crest',
      img: 'new-car/Crest.png',
      price: 708,
      oldPrice: 1200,
   },
   {
      id: cardCounter++,
      category: 'new-car',
      name: 'Устройство "Свободные руки"',
      brand: 'Silver Crest',
      img: 'new-car/Crest.png',
      price: 708,
      oldPrice: 1200,
   },
   // ==============    category: 'top-car'
   {
      id: cardCounter++,
      category: 'top-car',
      name: 'Авторегистратор Зеркало',
      brand: 'No Brand',
      img: 'top-car/Zer.png',
      price: 7800,
      oldPrice: 8777,
   },
   {
      id: cardCounter++,
      category: 'top-car',
      name: 'Авторегистратор Зеркало',
      brand: 'No Brand',
      img: 'top-car/Zer.png',
      price: 7800,
      oldPrice: 8777,
   },
   {
      id: cardCounter++,
      category: 'top-car',
      name: 'Авторегистратор Зеркало',
      brand: 'No Brand',
      img: 'top-car/Zer.png',
      price: 7800,
      oldPrice: 8777,
   },
   {
      id: cardCounter++,
      category: 'top-car',
      name: 'Авторегистратор Зеркало',
      brand: 'No Brand',
      img: 'top-car/Zer.png',
      price: 7800,
      oldPrice: 8777,
   },
   {
      id: cardCounter++,
      category: 'top-car',
      name: 'Авторегистратор Зеркало',
      brand: 'No Brand',
      img: 'top-car/Zer.png',
      price: 7800,
      oldPrice: 8777,
   },
   {
      id: cardCounter++,
      category: 'top-car',
      name: 'Авторегистратор Зеркало',
      brand: 'No Brand',
      img: 'top-car/Zer.png',
      price: 7800,
      oldPrice: 8777,
   },
   // ==============    category: 'popular-car'
   {
      id: cardCounter++,
      category: 'popular-car',
      name: 'Крутящиеся аромакольца',
      brand: 'Aroma',
      img: 'popular-car/Aroma.png',
      price: 359,
      oldPrice: 908,
   },
   {
      id: cardCounter++,
      category: 'popular-car',
      name: 'Крутящиеся аромакольца',
      brand: 'Aroma',
      img: 'popular-car/Aroma.png',
      price: 359,
      oldPrice: 908,
   },
   {
      id: cardCounter++,
      category: 'popular-car',
      name: 'Крутящиеся аромакольца',
      brand: 'Aroma',
      img: 'popular-car/Aroma.png',
      price: 359,
      oldPrice: 908,
   },
   {
      id: cardCounter++,
      category: 'popular-car',
      name: 'Крутящиеся аромакольца',
      brand: 'Aroma',
      img: 'popular-car/Aroma.png',
      price: 359,
      oldPrice: 908,
   },
   {
      id: cardCounter++,
      category: 'popular-car',
      name: 'Крутящиеся аромакольца',
      brand: 'Aroma',
      img: 'popular-car/Aroma.png',
      price: 359,
      oldPrice: 908,
   },
   {
      id: cardCounter++,
      category: 'popular-car',
      name: 'Крутящиеся аромакольца',
      brand: 'Aroma',
      img: 'popular-car/Aroma.png',
      price: 359,
      oldPrice: 908,
   },
   // ==============    category: 'new-cosmetics'
   {
      id: cardCounter++,
      category: 'new-cosmetics',
      name: 'Гель лак',
      brand: 'BABY Cold ',
      img: 'new-cosmetics/Cold.png',
      price: 71,
      oldPrice: 99,
   },
   {
      id: cardCounter++,
      category: 'new-cosmetics',
      name: 'Гель лак',
      brand: 'BABY Cold ',
      img: 'new-cosmetics/Cold.png',
      price: 71,
      oldPrice: 99,
   },
   {
      id: cardCounter++,
      category: 'new-cosmetics',
      name: 'Гель лак',
      brand: 'BABY Cold ',
      img: 'new-cosmetics/Cold.png',
      price: 71,
      oldPrice: 99,
   },
   {
      id: cardCounter++,
      category: 'new-cosmetics',
      name: 'Гель лак',
      brand: 'BABY Cold ',
      img: 'new-cosmetics/Cold.png',
      price: 71,
      oldPrice: 99,
   },
   {
      id: cardCounter++,
      category: 'new-cosmetics',
      name: 'Гель лак',
      brand: 'BABY Cold ',
      img: 'new-cosmetics/Cold.png',
      price: 71,
      oldPrice: 99,
   },
   {
      id: cardCounter++,
      category: 'new-cosmetics',
      name: 'Гель лак',
      brand: 'BABY Cold ',
      img: 'new-cosmetics/Cold.png',
      price: 71,
      oldPrice: 99,
   },
   // ==============    category: 'top-cosmetics'
   {
      id: cardCounter++,
      category: 'top-cosmetics',
      name: 'Портативный фрезер',
      brand: 'NAIL POLISHER',
      img: 'top-cosmetics/Nail.png',
      price: 214,
      oldPrice: 299,
   },
   {
      id: cardCounter++,
      category: 'top-cosmetics',
      name: 'Портативный фрезер',
      brand: 'NAIL POLISHER',
      img: 'top-cosmetics/Nail.png',
      price: 214,
      oldPrice: 299,
   },
   {
      id: cardCounter++,
      category: 'top-cosmetics',
      name: 'Портативный фрезер',
      brand: 'NAIL POLISHER',
      img: 'top-cosmetics/Nail.png',
      price: 214,
      oldPrice: 299,
   },
   {
      id: cardCounter++,
      category: 'top-cosmetics',
      name: 'Портативный фрезер',
      brand: 'NAIL POLISHER',
      img: 'top-cosmetics/Nail.png',
      price: 214,
      oldPrice: 299,
   },
   {
      id: cardCounter++,
      category: 'top-cosmetics',
      name: 'Портативный фрезер',
      brand: 'NAIL POLISHER',
      img: 'top-cosmetics/Nail.png',
      price: 214,
      oldPrice: 299,
   },
   {
      id: cardCounter++,
      category: 'top-cosmetics',
      name: 'Портативный фрезер',
      brand: 'NAIL POLISHER',
      img: 'top-cosmetics/Nail.png',
      price: 214,
      oldPrice: 299,
   },
   // ==============    category: 'popular-cosmetics'
   {
      id: cardCounter++,
      category: 'popular-cosmetics',
      name: 'Набор для ухода ',
      brand: 'Vitа С Perfect',
      img: 'popular-cosmetics/Vitа.png',
      price: 2744,
      oldPrice: 5444,
   },
   {
      id: cardCounter++,
      category: 'popular-cosmetics',
      name: 'Набор для ухода ',
      brand: 'Vitа С Perfect',
      img: 'popular-cosmetics/Vitа.png',
      price: 2744,
      oldPrice: 5444,
   },
   {
      id: cardCounter++,
      category: 'popular-cosmetics',
      name: 'Набор для ухода ',
      brand: 'Vitа С Perfect',
      img: 'popular-cosmetics/Vitа.png',
      price: 2744,
      oldPrice: 5444,
   },
   {
      id: cardCounter++,
      category: 'popular-cosmetics',
      name: 'Набор для ухода ',
      brand: 'Vitа С Perfect',
      img: 'popular-cosmetics/Vitа.png',
      price: 2744,
      oldPrice: 5444,
   },
   {
      id: cardCounter++,
      category: 'popular-cosmetics',
      name: 'Набор для ухода ',
      brand: 'Vitа С Perfect',
      img: 'popular-cosmetics/Vitа.png',
      price: 2744,
      oldPrice: 5444,
   },
   {
      id: cardCounter++,
      category: 'popular-cosmetics',
      name: 'Набор для ухода ',
      brand: 'Vitа С Perfect',
      img: 'popular-cosmetics/Vitа.png',
      price: 2744,
      oldPrice: 5444,
   },
   // ==============    category: 'new-pets'
   {
      id: cardCounter++,
      category: 'new-pets',
      name: 'Ошейник для собак',
      brand: 'WAUDOG',
      img: 'new-pets/Waudog.png',
      price: 171,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'new-pets',
      name: 'Ошейник для собак',
      brand: 'WAUDOG',
      img: 'new-pets/Waudog.png',
      price: 171,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'new-pets',
      name: 'Ошейник для собак',
      brand: 'WAUDOG',
      img: 'new-pets/Waudog.png',
      price: 171,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'new-pets',
      name: 'Ошейник для собак',
      brand: 'WAUDOG',
      img: 'new-pets/Waudog.png',
      price: 171,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'new-pets',
      name: 'Ошейник для собак',
      brand: 'WAUDOG',
      img: 'new-pets/Waudog.png',
      price: 171,
      oldPrice: 451,
   },
   {
      id: cardCounter++,
      category: 'new-pets',
      name: 'Ошейник для собак',
      brand: 'WAUDOG',
      img: 'new-pets/Waudog.png',
      price: 171,
      oldPrice: 451,
   },
   // ==============    category: 'top-pets'
   {
      id: cardCounter++,
      category: 'top-pets',
      name: 'Ошейник от блох',
      brand: 'Stop',
      img: 'top-pets/Stop.png',
      price: 44,
      oldPrice: 88,
   },
   {
      id: cardCounter++,
      category: 'top-pets',
      name: 'Ошейник от блох',
      brand: 'Stop',
      img: 'top-pets/Stop.png',
      price: 44,
      oldPrice: 88,
   },
   {
      id: cardCounter++,
      category: 'top-pets',
      name: 'Ошейник от блох',
      brand: 'Stop',
      img: 'top-pets/Stop.png',
      price: 44,
      oldPrice: 88,
   },
   {
      id: cardCounter++,
      category: 'top-pets',
      name: 'Ошейник от блох',
      brand: 'Stop',
      img: 'top-pets/Stop.png',
      price: 44,
      oldPrice: 88,
   },
   {
      id: cardCounter++,
      category: 'top-pets',
      name: 'Ошейник от блох',
      brand: 'Stop',
      img: 'top-pets/Stop.png',
      price: 44,
      oldPrice: 88,
   },
   {
      id: cardCounter++,
      category: 'top-pets',
      name: 'Ошейник от блох',
      brand: 'Stop',
      img: 'top-pets/Stop.png',
      price: 44,
      oldPrice: 88,
   },
   // ==============    category: 'popular-pets'
   {
      id: cardCounter++,
      category: 'popular-pets',
      name: 'Ошейник для дрессировки',
      brand: 'Lemfo',
      img: 'popular-pets/Lemfo.png',
      price: 1754,
      oldPrice: 2000,
   },
   {
      id: cardCounter++,
      category: 'popular-pets',
      name: 'Ошейник для дрессировки',
      brand: 'Lemfo',
      img: 'popular-pets/Lemfo.png',
      price: 1754,
      oldPrice: 2000,
   },
   {
      id: cardCounter++,
      category: 'popular-pets',
      name: 'Ошейник для дрессировки',
      brand: 'Lemfo',
      img: 'popular-pets/Lemfo.png',
      price: 1754,
      oldPrice: 2000,
   },
   {
      id: cardCounter++,
      category: 'popular-pets',
      name: 'Ошейник для дрессировки',
      brand: 'Lemfo',
      img: 'popular-pets/Lemfo.png',
      price: 1754,
      oldPrice: 2000,
   },
   {
      id: cardCounter++,
      category: 'popular-pets',
      name: 'Ошейник для дрессировки',
      brand: 'Lemfo',
      img: 'popular-pets/Lemfo.png',
      price: 1754,
      oldPrice: 2000,
   },
   {
      id: cardCounter++,
      category: 'popular-pets',
      name: 'Ошейник для дрессировки',
      brand: 'Lemfo',
      img: 'popular-pets/Lemfo.png',
      price: 1754,
      oldPrice: 2000,
   },
]


//колекция атрибутов миникарт
const dataMiniCard = document.querySelectorAll('[data-miniCard]')

//Перебираем все елементы на странице
dataMiniCard.forEach((item)=>{
   //Получаем каждый айтем с колекции
   const subject = item;
   //Получаем датасет с колекции 
   const datasetSubject = subject.dataset.minicard;

   //Делаем перебок нашего масива с товаром
   miniCardProduct.forEach((item)=>{
      //Получаем категорию  товара 
      const miniCardProductСategory =  item.category;

      // Если датасет равен категории масива 
      if(datasetSubject ===  miniCardProductСategory){
        
         //В шаблоную строку подставляем данные с масива
         const card = `<div class="product-card__mini" data-id="${item.id}">
                        <img class="card__img" src="./img/miniCard/${item.img}"  alt="">
                        <div class="card__description">
                           <span class="card__description-name">${item.name}</span>
                           <span class="card__description-brand">${item.brand}</span>
                           <div class="card__price">
                              <span class="card__price-new">${item.price}₴</span>
                              <span class="card__price-old">${item.oldPrice}₴</span>
                           </div>
                        </div>
                           <div class="card__buttons">
                              <div class="items">
                                 <div class="items__control" data-action="minus">-</div>
                                 <div class="items__current" data-counter="">1</div>
                                 <div class="items__control" data-action="plus">+</div>
                              </div>
                              <button class="btn-like"></button>
                              <button class="btn-cart" data-cart ></button>
                           </div>
                     </div>`;

         //Рендерим товар в наши айтемы которые мы получили из колекции 
         subject.insertAdjacentHTML('beforeend', card)
         
      }

   })

})


